# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('react_drf', '0002_local'),
    ]

    operations = [
        migrations.RenameField(
            model_name='local',
            old_name='metrople',
            new_name='metropole',
        ),
    ]
