# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('react_drf', '0003_auto_20161121_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('pdf', models.FileField(upload_to='/pdf')),
            ],
        ),
    ]
