# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('react_drf', '0004_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='pdf',
            field=models.FileField(upload_to='pdf'),
        ),
    ]
